### ISSUE TITLE
Type mismatch in message

### ISSUE THREAD

**Issue by ghost** [Innovailable/calling-signaling#1]
Every time i try to send any message i get the same answer: "Type mismatch in message".
Ex:

//request
{
  "type": "ns_subscribe",
  "tid": "a0fde8a8-f863-4e40-86d1-566555eaf2dc", // the id i get on connect
  "namespace": "test"
}

//answer
{"type":"answer","tid":"a0fde8a8-f863-4e40-86d1-566555eaf2dc","error":"Type mismatch in message"}

What is wrong?

**Comment by thammi** [comment]
The `tid` is the transaction id, not your user id. You can choose any integer/number as transaction id, but it should be unique for each message (not enforeced by server). You can count up from zero for an easy implementation. It will be included in the answer to help you match the answer to your request.

**Comment by ghost** [comment]
Thank you for your help! ;)
